name: ci

on: [push]
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker_service: ['node-code', 'php-code', 'python-code', 'golang-code']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build docker images
      run: docker-compose up --build $DOCKER_SERVICE
      env:
        DOCKER_SERVICE: ${{ matrix.docker_service }}

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3

    - name: Run sonarqube
      run: sonar-scanner
           -Dsonar.host.url=https://sonarcloud.io/
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}